# Generated by Django 2.0.1 on 2018-01-25 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20180125_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='diets',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
