# Generated by Django 2.0.1 on 2018-01-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20180125_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='days',
            name='description',
            field=models.CharField(default='', max_length=600),
        ),
    ]
